command:
  help: '%teracore_prefix% &eâ“ &7Verwende: /banlist <Seite>'
  permission: 'teracore.banlist'
  message:
    split: '%teracore_prefix% &7ğŸ“„ Banliste - Seite &e%seite% &7von &e%max%'
    info: '&7ğŸ‘¤ Spieler: &e%player%, &7â³ Dauer: &e%time%'
