command:
  # Hilfe-Nachricht, die den Spielern erklÃ¤rt, wie der Teleport-Befehl verwendet wird
  help: '%teracore_prefix% &eâ“ &7/%command% <Spieler>'

  # Argument 1: Teleportiert den Spieler zu einer Location oder einem anderen Spieler
  args1:

    # Nachricht bei gesendeter Anfrage
    quest: '%teracore_prefix% &eğŸ“¨ &7Deine &e/%command% &7-Anfrage wurde erfolgreich gesendet!'

    failed: '%teracore_prefix% &câœ– Du hast dem Spieler bereits eine Anfrage gesendet!'

    empty: '%teracore_prefix% &câœ– Der Spieler %trust_name% hat dir keine Anfrage gesendet!'

    trust:
      text:
        - '%teracore_prefix% &eğŸ“¥ &7Du hast eine %command%-Anfrage erhalten!'
        - '%teracore_prefix% &eğŸ‘¤ &7Von: &e%trust_name%'
        - '%teracore_prefix% &7Antworte mit &a%accept% &7oder &c%deny%&7.'

      hover:
        accept:
          text: '&aAnnehmen'
          hover: '&aâœ… Anfrage annehmen'
          click: '/tpaccept %trust_name%'
          player: '%teracore_prefix% &aâœ” Deine Teleport-Anfrage wurde angenommen!'
          trust: '%teracore_prefix% &aâœ” Du hast die Teleport-Anfrage angenommen!'

        deny:
          text: '&cAblehnen'
          hover: '&câŒ Anfrage ablehnen'
          click: '/tpadeny %trust_name%'
          player: '%teracore_prefix% &câœ˜ Deine Teleport-Anfrage wurde abgelehnt!'
          trust: '%teracore_prefix% &câœ˜ Du hast die Teleport-Anfrage abgelehnt!'

    # Berechtigungen fÃ¼r die Nutzung der jeweiligen Teleport-Befehle
    permission:
      tpa: 'teracore.tpa'             # Berechtigung fÃ¼r /tpa
      tpahere: 'teracore.tpahere'     # Berechtigung fÃ¼r /tpahere
      tpaccept: 'teracore.tpaccept'   # Berechtigung fÃ¼r /tpaccept
      tpadeny: 'teracore.tpadeny'     # Berechtigung fÃ¼r /tpadeny
