placeholder:
  # Platzhalter fÃ¼r verschiedene Wetterarten
  clear: 'â˜€ Sonne'       # Klare Wetterbedingungen
  rain: 'ğŸŒ§ Regen'        # Regenwetter
  thunder: 'â›ˆ Sturm'      # Gewitterwetter

command:
  # Hilfe-Nachricht, die zeigt, wie der Befehl verwendet wird
  help: '%teracore_prefix% &eâ“ &7/weather <Clear/Rain/Thunder>'
  
  args1:
    # Nachricht, die angezeigt wird, wenn das Wetter erfolgreich geÃ¤ndert wurde
    usage: '%teracore_prefix% &eâ˜ &7Das Wetter wurde auf &e%weather% &7geÃ¤ndert!'
    
    # Berechtigung, die erforderlich ist, um eine bestimmte Wetterart zu setzen
    permission: 'teracore.weather.%weather%'
