command:
  # Hilfe-Nachricht, die den Spielern erklÃ¤rt, wie der Befehl verwendet wird
  help: '%teracore_prefix% &eâ“ &7/skull <Spieler>'
  
  args1:
    # Nachricht, die den Spieler darÃ¼ber informiert, dass er den Kopf eines anderen Spielers erhalten hat
    usage: '%teracore_prefix% &eğŸ’€ &7Du hast den Kopf von &e%trust% &7erhalten!'
    
    # Berechtigung, die erforderlich ist, um den Befehl auszufÃ¼hren
    permission: 'teracore.skull'
